#!/bin/bash

anyattr base && skiptask "baz sistem"

# ------------------------------------------------------------------------------
# Her makinede (grafik ortam bulunmayan sunucular dahil) kurulacak paketler
#
# Dikkat!  Bu kategorideki Gem'lerin ağır bir bağımlılığı olmamalı.  Özellikle X
# Window'a bağımlı hiçbir paket olmamalı.
# ------------------------------------------------------------------------------

GEM_BASE="
bundler
gist
github
git-pulls
grit
gx
haml
json
launchy
mime-types
octopussy
thor
ya2yaml
"

# ------------------------------------------------------------------------------
# Tipik bir masaüstü ortamda kurulacak paketler
#
# Dikkat!  Bu kategoride graif ortamda çalışabilecek paketler olabilir.  Fakat
# paket bağımlılığı sorunları azaltmak için karmaşık bağımlılığa sahip paketler
# kurmaktan kaçının.
# ------------------------------------------------------------------------------

GEM_STANDARD="
irbtools
irbtools-more
jekyll
kramdown
nokogiri
ronn
"

# ------------------------------------------------------------------------------
# Geliştirme ortamı olarak kullanacağımız bir makinede kurulacak ekstra paketler
# ------------------------------------------------------------------------------

GEM_EXTRA="
chunky_png
gdata4ruby
gdocs4ruby
methopara
oily_png
pythonconfig
rdp-arguments
rvm
"

hascommand ruby1.9.1 || hascommand gem1.9.1 || hascommand ruby || hascommand gem || {
	cry "Ruby kurulu değil."
	exit 0
}

if ! anyattr server && anyattr gui &&
   yesno "Ekstra Ruby Gem'leri kurulsun mu?" e; then
	setattr fat
fi

sudoattempt

installgems "Temel Gem paketleri kuruluyor" $GEM_BASE
if ! anyattr server && anyattr gui fat; then
	installgems "Standart bir çalışma ortamı için gerekli Gem paketleri kuruluyor" \
		$GEM_STANDARD
fi
if anyattr fat; then
	installgems "Geliştirici ortamı için gerekli ekstra Gem paketleri kuruluyor" \
		$GEM_EXTRA
fi
