#!/bin/bash

anyattr base && skiptask "baz sistem"

hascommand ruby || skiptask "ruby kurulu değil"

# vim eklentilerini güncelleme betiği
vimpluginupdateprog="./bin/vim-update-bundles"
[ -x "$vimpluginupdateprog" ] || die "$vimpluginupdateprog bulunamadı."

say "Vim eklentileri kuruluyor/güncelleniyor..."
$vimpluginupdateprog

if ! anyattr server; then
	say "Paket indisleri güncelleniyor..."

	sudoattempt
	xaptget update ||:

	installdebs "YouCompleteMe eklentisi kuruluyor" vim-addon-manager vim-youcompleteme && vam install youcompleteme
fi
