#!/bin/bash

COMMANDT_BUNDLE=".vim/bundle/Command-T"
COMMANDT_EXT="ruby/command-t"

GOCODE_PKG=github.com/nsf/gocode
GOCODE_DIR="${GOROOT:-/usr/lib/go}/src/pkg/${GOCODE_PKG}"

anyattr base && skiptask "baz sistem"

hascommand ruby || skiptask "ruby kurulu değil"

# Command-T eklentisinin depo durumunu kurulum öncesinde not et
git_head_follow "./${COMMANDT_BUNDLE}"

# vim eklentilerini güncelleme betiği
vimpluginupdateprog="./bin/vim-update-bundles"
[ -x "$vimpluginupdateprog" ] || die "$vimpluginupdateprog bulunamadı."

say "Vim eklentileri kuruluyor/güncelleniyor..."
$vimpluginupdateprog

if ! anyattr server; then
	say "Paket indisleri güncelleniyor..."

	sudoattempt
	xaptget update ||:

	installdebs "YouCompleteMe eklentisi kuruluyor" vim-addon-manager vim-youcompleteme && vam install youcompleteme
fi
