#!/bin/bash

anyattr base server && skiptask "baz veya sunucu ortamı"

hascommand gnome-session || skiptask "GNOME kurulu değil"

SRC_ALTERNATIVES="
	/usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring.c
	/tmp/git-credential-gnome-keyring.c
"

DEST=/usr/local/bin/git-credential-gnome-keyring
for f in $SRC_ALTERNATIVES; do
	if [ -f "$f" ]; then
		SRC="$f"
	fi
done

[ -n "$SRC" ] || skiptask "Şu kaynak dosyalardan herhangi bir bulunamadı: " $SRC_ALTERNATIVES

say "Gerekli kaynak bulundu; kurulum yapılıyor..."

sudoattempt

xaptget install build-essential libgnome-keyring-dev ||:
sudo gcc -g -O2 -Wall \
	$(pkg-config --cflags gnome-keyring-1) \
	$(pkg-config --libs gnome-keyring-1) \
	-o "$DEST" "$SRC" || err=$?
if [ -n "$err" ] || [ ! -x "$DEST" ]; then
	cry "Kurulum başarısız."

fi
