#!/bin/bash

GEM_BASE="
sinatra
"

if anyattr gui; then
	cry "Bu bir masaüstü sistem gibi görünüyor. " \
	    "Böyle bir sisteme sunucu kurmamalısınız."
	if ! yesno "Yine de devam edilsin mi?" h; then
		cry "Güzel!"
		exit
	fi
fi

taskrun 2 genel-sunucu

sudoattempt
installgems "Sinatra Gem paketleri kuruluyor" $GEM_BASE
